Update README.md
launchdarkly/hello-js pull request #3
Opened 2020-01-07 03:29 UTC by UPatel12

added #3 to the readme

2020-01-07 20:19 UTC, bwoskow-ld requested changes
Thanks for the contribution! I made a minor request to be addressed before we go ahead and merge this.

2020-01-07 20:19 UTC, bwoskow-ld commented on README.md
> +3. Copy your CLIENT_SIDE_ID from your LaunchDakly Account Settings page into `index.html` 
Change to:

> Copy your client-side ID from your LaunchDarkly Account Settings page into `index.html`

2022-01-31 17:29 UTC, ember-stevens commented on README.md
> +3. Copy your CLIENT_SIDE_ID from your LaunchDakly Account Settings page into `index.html` 
```suggestion
3. Copy your client-side ID from your LaunchDarkly Account Settings page into `index.html` 
```

2022-01-31 19:29 UTC, bwoskow-ld approved these changes

2022-01-31 19:30 UTC, merged